services:
  web-db:
    extends: 
      file: ../web-service/docker-compose.yml
      service: web-db
  web-service:
    extends: 
      file: ../web-service/docker-compose.yml
      service: web-service
  soap-db:
    extends: 
      file: ../soap-service/docker-compose.yml
      service: soap-db
  soap-service:
    extends: 
      file: ../soap-service/docker-compose.yml
      service: soap-service
  rest-service-db:
    extends:
      file: ../rest-service/docker-compose.yml
      service: rest-service-db
  rest-service:
    extends:
      file: ../rest-service/docker-compose.yml
      service: rest-service
  client-webapp:
    extends:
      file: ../client-webapp/docker-compose.yml
      service: client-webapp
  redis:
    extends:
      file: ../rest-service/docker-compose.yml
      service: redis
