services:
  db:
    extends: 
      file: ../web-service/docker-compose.yml
      service: db
  php-apache:
    extends: 
      file: ../web-service/docker-compose.yml
      service: php-apache
  phpmyadmin:
    extends: 
      file: ../web-service/docker-compose.yml
      service: phpmyadmin
  soap-db:
    extends: 
      file: ../soap-service/docker-compose.yml
      service: soap-db
  soap-service:
    extends: 
      file: ../soap-service/docker-compose.yml
      service: soap-service
  rest-service-db:
    extends:
      file: ../rest-service/docker-compose.yml
      service: rest-service-db
  rest-service:
    extends:
      file: ../rest-service/docker-compose.yml
      service: rest-service
  client-webapp:
    extends:
      file: ../client-webapp/docker-compose.yml
      service: client-webapp